# tweet-scraper parameters

# TEMPLATE FILE
#  copy this file, name it "config.yaml" and insert the given keys into the given parameters.
#  double check that "config.yaml" is in .gitignore and .dockerignore
#  DO NOT PUBLISH ANY TOKENS ON GITHUB
#  if you do, please notify us before resetting the tokens.

# twitter tokens
tokens:
  twitter:
    consumer_key: "KEY HERE"
    consumer_secret: "KEY HERE"
    access_token_key: "KEY HERE"
    access_token_secret: "KEY HERE"

#the standard parameters for the stream, the server is caching it's tweets from
tweetParams:
  #bounding box of enclosed area.
  # WGS84: "WEST,SOUTH,EAST,NORTH"

  locations: "5.00,47.15,15.20,55.22"
  #track params can only be up to 60 bytes
  track: "klima, regen, sturm, unwetter, hilfe"

# weather scraper parameters
weatherParams:
  weatherUpdateInterval: 300000
