# tweet-scraper parameters

# twitter tokens
tokens:
  twitter:
    consumer_key: "M2ZROT74Nu4TNBPUQLVtaRbsm"
    consumer_secret: "Bx7iLqgbjSvxCI8kOK6CdTgGvoaUJpzV7GCuiXffPT306HF4AF"
    access_token_key: "1198826533047197696-zRftsydr4rF93pJSBalRg05AEE88Ao"
    access_token_secret: "LleRa86TeSWdAOJiy0leKsRMGla5OGwV2hdiaZnB1v9Ux"

#the standard parameters for the stream, the server is caching it's tweets from
tweetParams:
  #bounding box of enclosed area.
  # WGS84: "WEST,SOUTH,EAST,NORTH"

  locations: "5.00,47.15,15.20,55.22"
  #track params can only be up to 60 bytes
  track: "klima, regen, sturm, unwetter, hilfe"

# weather scraper parameters
weatherParams:
  weatherUpdateInterval: 300000
